### ISSUE TITLE
"Unable to open a display" Error when Running Image Generation

### ISSUE THREAD

**Issue by Relento** [michaal94/shop-vrb-gen#1]
Hi!

 I just try to run the image generation code, but it always exits abnomaly and displays "Unable to open a display".  By some tweak, I found that the code always stuck at line 705 of `render_images.py`:

`bpy.ops.render.render(write_still=True)`

I have tried both blender 2.81a and 2.82a.

I am wondering how can I fix this.
Thanks!

**Comment by michaal94** [comment]
That is the issue with new Blender versions. I suggest you to read [this post](https://devtalk.blender.org/t/blender-2-8-unable-to-open-a-display-by-the-rendering-on-the-background-eevee/1436/29). I assume you are trying to run the code remotely. Even though the code does not use a display, Blender >=2.8x still tries to open a display. However, making a virtual display described in the post above should work.  

If you are accessing a machine with physical displays remotely you may encounter such error:
```Fatal server error:
(EE) Cannot establish any listening sockets - Make sure an X server isn't already running(EE) 
(EE) 
Please consult the The X.Org Foundation support 
	 at http://wiki.x.org
 for help. 
(EE) Please also check the log file at "/var/log/Xorg.0.log" for additional information.
(EE) 
(EE) Server terminated with error (1). Closing log file.
```
If that happens, that means that there is already Xorg session running and you have to stop it (e.g. `sudo kill -9 [pid]` where `[pid]` can be obtained from `ps -C Xorg`. After doing that you should be able to run a new Xorg session with a virtual display included.

**Comment by Relento** [comment]
Thank you! The post is very helpful. Problem Resolved.
